# This file contains default configuration.
#
# Additional config files:
#   Development: appsettings.Development.yml
#   Production:  appsettings.Production.yml
#   Kubernetes:  values.yaml + helmfile.yaml
#   Local IDE:   launchSettings.json

Logging:
  LogLevel:
    Default: Information

Dummy:
  Sleep: 00:00:10 # 10 seconds
