# This file contains default configuration.
#
# Additional config files:
#   dev:        appsettings.Development.yml
#   live:       appsettings.Production.yml
#   Kubernetes: helmfile.yaml
#   local dev:  launchSettings.json

Dummy:
  Sleep: 00:00:10 # 10 seconds
