helmDefaults:
  force: true # Allow deploying over failed releases
  wait: true # Wait for all Pods to become ready

# Registers repos for use in requirements.yaml
repositories:
  - name: axoom-github
    url: https://axoom.github.io/charts/

# Installs charts
releases:
  - name: myvendor-myservice
    namespace: myteam
    chart: ./charts/myvendor-myservice

    values:
      - app:
          image:
            tag: '{{ requiredEnv "GitVersion_NuGetVersion" }}'
          env:
            ENVIRONMENT: '{{ env "ENVIRONMENT" | default "Production" }}'
