# Registers repos for use in requirements.yaml
repositories:
  - name: axoom-github
    url: https://axoom.github.io/charts/

# Maps environment variables to Helm options and values
releases:
  - name: 'myvendor-myservice{{ env "NAME_SUFFIX" }}'
    namespace: 'myteam{{ env "NAME_SUFFIX" }}'
    chart: ./charts/myvendor-myservice

    values:
      - app:
          image:
            tag: '{{ requiredEnv "GitVersion_NuGetVersion" }}'
          env:
            ENVIRONMENT: '{{ env "ENVIRONMENT" | default "Production" }}'
