Logging:
  ApplicationName: myservice
  LogTargets:
    0:
      Type: Console
      Async: true
      Format: Plain
      Level: Debug

Policies:
  StartupRetries:
    - 00:00:15
    - 00:00:30
